spring:

# jpa auditing overriding
  main:
    allow-bean-definition-overriding: true

  server:
    port: 8880
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

  # vue + spring setting
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist

# 시큐리티 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# db 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/hyeong
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

# Redis 설정
  redis:
#    host: 127.0.0.1
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2

# jpa 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #show_sql: true

#jwt 설정
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400 # 1day
  accessToken-validity-in-seconds: 1800 #30 min
  refreshToken-validity-in-seconds: 604800 # 1week

# logging 설정
logging.level:
  org.hibernate.SQL: debug
  ##org.hibernate.type: trace

# 서울시 공공 api 설정
open-api:
  seoul:
    address: http://openapi.seoul.go.kr:8088/
    auth-key: 47766869696775643130396941575a4d
    type: json
    service-name: CardSubwayTime